export const abi = [{
	type: "constructor",
	inputs: [{
		name: "_nft",
		type: "address",
		internalType: "address"
	}, {
		name: "_feeTo",
		type: "address",
		internalType: "address payable"
	}],
	stateMutability: "nonpayable"
}, {
	type: "function",
	name: "HOLD_FEE_C",
	inputs: [],
	outputs: [{
		name: "",
		type: "uint256",
		internalType: "uint256"
	}],
	stateMutability: "view"
}, {
	type: "function",
	name: "HOLD_FEE_P",
	inputs: [],
	outputs: [{
		name: "",
		type: "uint256",
		internalType: "uint256"
	}],
	stateMutability: "view"
}, {
	type: "function",
	name: "MILLI",
	inputs: [],
	outputs: [{
		name: "",
		type: "uint256",
		internalType: "uint256"
	}],
	stateMutability: "view"
}, {
	type: "function",
	name: "MINT_FEE",
	inputs: [],
	outputs: [{
		name: "",
		type: "uint256",
		internalType: "uint256"
	}],
	stateMutability: "view"
}, {
	type: "function",
	name: "MIN_INTERVAL",
	inputs: [],
	outputs: [{
		name: "",
		type: "uint256",
		internalType: "uint256"
	}],
	stateMutability: "view"
}, {
	type: "function",
	name: "PERCENT",
	inputs: [],
	outputs: [{
		name: "",
		type: "uint256",
		internalType: "uint256"
	}],
	stateMutability: "view"
}, {
	type: "function",
	name: "VAT_C",
	inputs: [],
	outputs: [{
		name: "",
		type: "uint256",
		internalType: "uint256"
	}],
	stateMutability: "view"
}, {
	type: "function",
	name: "VAT_P",
	inputs: [],
	outputs: [{
		name: "",
		type: "uint256",
		internalType: "uint256"
	}],
	stateMutability: "view"
}, {
	type: "function",
	name: "WNFT_TYPEHASH",
	inputs: [],
	outputs: [{
		name: "",
		type: "bytes32",
		internalType: "bytes32"
	}],
	stateMutability: "view"
}, {
	type: "function",
	name: "burn",
	inputs: [{
		name: "tokenId",
		type: "uint256",
		internalType: "uint256"
	}],
	outputs: [],
	stateMutability: "nonpayable"
}, {
	type: "function",
	name: "buy",
	inputs: [{
		name: "tokenId",
		type: "uint256",
		internalType: "uint256"
	}, {
		name: "buyPrice",
		type: "uint256",
		internalType: "uint256"
	}, {
		name: "sellPrice",
		type: "uint256",
		internalType: "uint256"
	}],
	outputs: [],
	stateMutability: "payable"
}, {
	type: "function",
	name: "eip712Domain",
	inputs: [],
	outputs: [{
		name: "fields",
		type: "bytes1",
		internalType: "bytes1"
	}, {
		name: "name",
		type: "string",
		internalType: "string"
	}, {
		name: "version",
		type: "string",
		internalType: "string"
	}, {
		name: "chainId",
		type: "uint256",
		internalType: "uint256"
	}, {
		name: "verifyingContract",
		type: "address",
		internalType: "address"
	}, {
		name: "salt",
		type: "bytes32",
		internalType: "bytes32"
	}, {
		name: "extensions",
		type: "uint256[]",
		internalType: "uint256[]"
	}],
	stateMutability: "view"
}, {
	type: "function",
	name: "feeTo",
	inputs: [],
	outputs: [{
		name: "",
		type: "address",
		internalType: "address payable"
	}],
	stateMutability: "view"
}, {
	type: "function",
	name: "getHoldFee",
	inputs: [{
		name: "tokenId",
		type: "uint256",
		internalType: "uint256"
	}, {
		name: "choice",
		type: "uint8",
		internalType: "uint8"
	}],
	outputs: [{
		name: "",
		type: "uint256",
		internalType: "uint256"
	}],
	stateMutability: "view"
}, {
	type: "function",
	name: "getMintFee",
	inputs: [{
		name: "price",
		type: "uint256",
		internalType: "uint256"
	}],
	outputs: [{
		name: "mintFee",
		type: "uint256",
		internalType: "uint256"
	}],
	stateMutability: "pure"
}, {
	type: "function",
	name: "getSignHash",
	inputs: [{
		name: "owner",
		type: "address",
		internalType: "address"
	}, {
		name: "nftAddr",
		type: "address",
		internalType: "address"
	}, {
		name: "tokenId",
		type: "uint256",
		internalType: "uint256"
	}, {
		name: "price",
		type: "uint256",
		internalType: "uint256"
	}],
	outputs: [{
		name: "",
		type: "bytes32",
		internalType: "bytes32"
	}],
	stateMutability: "view"
}, {
	type: "function",
	name: "getWNFT",
	inputs: [{
		name: "tokenId",
		type: "uint256",
		internalType: "uint256"
	}],
	outputs: [{
		name: "",
		type: "tuple",
		internalType: "struct Market.WNFT",
		components: [{
			name: "deadline",
			type: "uint256",
			internalType: "uint256"
		}, {
			name: "isPaid",
			type: "bool",
			internalType: "bool"
		}, {
			name: "isListed",
			type: "bool",
			internalType: "bool"
		}, {
			name: "isExpired",
			type: "bool",
			internalType: "bool"
		}, {
			name: "interval",
			type: "uint16",
			internalType: "uint16"
		}, {
			name: "owner",
			type: "address",
			internalType: "address"
		}, {
			name: "tokenId",
			type: "uint256",
			internalType: "uint256"
		}, {
			name: "price",
			type: "uint256",
			internalType: "uint256"
		}, {
			name: "lastDealPrice",
			type: "uint256",
			internalType: "uint256"
		}]
	}],
	stateMutability: "view"
}, {
	type: "function",
	name: "isExpired",
	inputs: [{
		name: "tokenId",
		type: "uint256",
		internalType: "uint256"
	}],
	outputs: [{
		name: "",
		type: "bool",
		internalType: "bool"
	}],
	stateMutability: "nonpayable"
}, {
	type: "function",
	name: "isOnsale",
	inputs: [{
		name: "tokenId",
		type: "uint256",
		internalType: "uint256"
	}],
	outputs: [{
		name: "",
		type: "bool",
		internalType: "bool"
	}],
	stateMutability: "view"
}, {
	type: "function",
	name: "list",
	inputs: [{
		name: "tokenId",
		type: "uint256",
		internalType: "uint256"
	}, {
		name: "price",
		type: "uint256",
		internalType: "uint256"
	}, {
		name: "sellerSign",
		type: "bytes",
		internalType: "bytes"
	}],
	outputs: [],
	stateMutability: "nonpayable"
}, {
	type: "function",
	name: "mint",
	inputs: [{
		name: "tokenId",
		type: "uint256",
		internalType: "uint256"
	}, {
		name: "price",
		type: "uint256",
		internalType: "uint256"
	}, {
		name: "interval",
		type: "uint16",
		internalType: "uint16"
	}, {
		name: "originURI",
		type: "string",
		internalType: "string"
	}],
	outputs: [],
	stateMutability: "payable"
}, {
	type: "function",
	name: "nft",
	inputs: [],
	outputs: [{
		name: "",
		type: "address",
		internalType: "address"
	}],
	stateMutability: "view"
}, {
	type: "function",
	name: "nonces",
	inputs: [{
		name: "owner",
		type: "address",
		internalType: "address"
	}],
	outputs: [{
		name: "",
		type: "uint256",
		internalType: "uint256"
	}],
	stateMutability: "view"
}, {
	type: "function",
	name: "payHoldFee",
	inputs: [{
		name: "tokenId",
		type: "uint256",
		internalType: "uint256"
	}],
	outputs: [],
	stateMutability: "payable"
}, {
	type: "function",
	name: "soldOut",
	inputs: [{
		name: "tokenId",
		type: "uint256",
		internalType: "uint256"
	}],
	outputs: [],
	stateMutability: "nonpayable"
}, {
	type: "event",
	name: "EIP712DomainChanged",
	inputs: [],
	anonymous: false
}, {
	type: "event",
	name: "NFTExpired",
	inputs: [{
		name: "tokenId",
		type: "uint256",
		indexed: true,
		internalType: "uint256"
	}, {
		name: "owner",
		type: "address",
		indexed: true,
		internalType: "address"
	}, {
		name: "price",
		type: "uint256",
		indexed: false,
		internalType: "uint256"
	}, {
		name: "deadline",
		type: "uint256",
		indexed: false,
		internalType: "uint256"
	}],
	anonymous: false
}, {
	type: "error",
	name: "ECDSAInvalidSignature",
	inputs: []
}, {
	type: "error",
	name: "ECDSAInvalidSignatureLength",
	inputs: [{
		name: "length",
		type: "uint256",
		internalType: "uint256"
	}]
}, {
	type: "error",
	name: "ECDSAInvalidSignatureS",
	inputs: [{
		name: "s",
		type: "bytes32",
		internalType: "bytes32"
	}]
}, {
	type: "error",
	name: "InvalidAccountNonce",
	inputs: [{
		name: "account",
		type: "address",
		internalType: "address"
	}, {
		name: "currentNonce",
		type: "uint256",
		internalType: "uint256"
	}]
}, {
	type: "error",
	name: "InvalidShortString",
	inputs: []
}, {
	type: "error",
	name: "ReentrancyGuardReentrantCall",
	inputs: []
}, {
	type: "error",
	name: "StringTooLong",
	inputs: [{
		name: "str",
		type: "string",
		internalType: "string"
	}]
}]
